### ISSUE TITLE
can not select/delete projects from list

### ISSUE THREAD

**Issue by outsmartit** [Bixie/pagekit-portfolio#1]
I can not select a project from the project list by clicking the check box, although the counter is always augmented (saying I have selected 6 projects although I have only created 1).  As a consequence, i can not delete the project.

I also have a problem with the thumbnail images.  Thumbnails point to localhost/tmp/portfolio ... while they are physically stored in localhost/pagekit/tmp/portfolio.  This worked on a previous version.

br,

Diederik

**Comment by outsmartit** [comment]
Project selection issue has been solved in the latest release.
However, the thumbnail issue is persisting.  Seems to me that method PortfolioImageHelper->resizeImage returns a path starting with "/", which causes the error.  Omitting the / at the start solves the problem.

**Comment by malles** [comment]
Sorry, I had not seen this issue, or I would have solved that before the release. The selection bug I spotted myself too :)

**Comment by djayko** [comment]
Hi,

if redirect base in htaccess is different, the <img src - link to the thumbnails is wrong (the url folder is missed)
