### ISSUE TITLE
How to change the /portfolio/ url-slug to something else ?

### ISSUE THREAD

**Issue by philipsiwinski** [Bixie/pagekit-portfolio#12]
Hi, many thanks for your extension, it's really neat ^^

I was wondering if it would be possible to add a setting to change the url / slug which currently is /portfolio.

Thanks :-)

**Comment by malles** [comment]
The slug /portfolio is the name of the default node placed in your site tree (default at Not assigned). You can change the name and slug of that node in the Site settings.

**Comment by philipsiwinski** [comment]
Great help! Thanks a lot, I haven't seen that.
