### ISSUE TITLE
Lightbox image description is at outside 

### ISSUE THREAD

**Issue by ghost** [Bixie/pagekit-portfolio#15]
According to image ratio, description goes out of window.
Here is an image of it. Opera and Chrome and Tor.
![capture](https://cloud.githubusercontent.com/assets/1254613/14903836/9e3e1e9a-0dac-11e6-8b7a-80cacd8d0113.PNG)

**Comment by malles** [comment]
This is done by the UIkit lightbox css. You could change the style of the lightbox bia css to have the title inside the image;

```
.uk-modal .uk-modal-caption {
     bottom: 20px;
}
```
