### ISSUE TITLE
Project properties [image main/teaser] are not workinkg correctly

### ISSUE THREAD

**Issue by djluki555** [Bixie/pagekit-portfolio#20]
I encountered a problem when I wanted to use the files with long names. 
I tried to find the problem and it turned out that the JSON in the "image" column in the database is truncated. I conclude that the problem is too small size of this column.

**Comment by malles** [comment]
I see this is an issue with installations prior to 1.1.4. It is hard to fix in an update, but you can fix it yourself easily via phpmyadmin.
![image](https://cloud.githubusercontent.com/assets/5442402/20793257/72481042-b7c6-11e6-8be6-0c2436e94cf1.png)
Go to your table `xx_portfolio_project` and click the structure tab. Then click edit on the `images` column.
Change the type from TINYTEXT to LONGTEXT and save.
