### ISSUE TITLE
Display Project... short code?

### ISSUE THREAD

**Issue by sulivieri** [Bixie/pagekit-portfolio#23]
Hi,
sorry for the question, maybe i miss something, but...
how do you put a gallery-project into a page and/or widget?

actually i create a gallery,
took the link and put into a menu-link
so the gallery is displayed into the page
but if i want, for example, put the gallery into homepage?

Update:
oki, i found portfolio into 'not linked' page.
set as homepage and now it's displayed into homepage
but it show me just the main folder, not thumbnails.

are short code implemented?

thanks

**Comment by malles** [comment]
There is no shortcode implemented. You can set the number of image thumbnails shown in the teaser in the image settings.
