### ISSUE TITLE
Lightbox not working

### ISSUE THREAD

**Issue by Dylface** [Bixie/pagekit-portfolio#26]
I choose an image folder for the gallery and save the portfolio.

I then go onto my site and refresh it, but all the images show in a list and aren't clickable / don't pop up using lightbox.

Do I need to do anything more to get this working? Tried adding the lightbox script into my HTML body, but it doesn't make a difference..

http://dylanlopes.com/portfolio

**Comment by svondervoort** [comment]
Looks like it's working now?

**Comment by Dylface** [comment]
Yeah, I changed to a fresh template, and started redoing my own CSS styling. So there was obviously a conflict somewhere that I couldn't find. cheers.
