### ISSUE TITLE
Project Title field validation error

### ISSUE THREAD

**Issue by shoostar** [Bixie/pagekit-portfolio#6]
When creating a new project, entering any combination of characters will not register as a valid project title. This occurs when moving focus away from this field, whether it be from clicking elsewhere, or using Tab to move to next field.

![Project Title validation error](http://i.imgur.com/7XB5YLZ.png)

**Comment by malles** [comment]
Somehow my dev-installation was out of sync. Validation did work there. https://github.com/Bixie/pagekit-portfolio/commit/60c270dc8855c5bdc43334bdf9713b93c5288ba2
This commit should fix it, will release in a short while.
Thanks for reporting
