### ISSUE TITLE
Project not saving images

### ISSUE THREAD

**Issue by shoostar** [Bixie/pagekit-portfolio#7]
I really hate to be a bother, but it seems a couple new issues have popped up in this extension. Not only do projects not save images, but the ability to upload an image folder has also been disabled. Confirmed on a clean install using MySQL and SQLite.

A quick rundown of the process I'm following: click "Add Project", fill out all info (project title validates properly now, thanks!), click on Images tab. In this tab, the user has the option to upload a main image, a teaser image, and an image folder. Both the main and teaser images seem to upload properly, and initially display their respective image previews, but upon clicking "Save" and returning to the main Portfolio listing page, these images seem to end up lost somewhere. Going back into this project to make edits, a user can navigate to the Images tab again, and the main and teaser images are gone. They're still in the uploaded media folder, just not in the project itself.

Also, as mentioned above, there seems to be no way to upload an image folder to a project anymore. Under the main and teaser image preview area, there's just a blank box that says "Image Folder", and nothing else like there was before.

Again, I'm really sorry to be a pain in the ass, so don't shoot the messenger please :)

**Comment by malles** [comment]
I'm the pain in my own ass :) I did test that at one stage, but it must have gotten broken somewhere.
I'm glad that you tell me, so I can fix it, no problem.

**Comment by shoostar** [comment]
Just wanted to report back with good news: everything seems to be in order and works just fine now! Thanks for all your hard work, I'm excited to get back to working on a couple projects using this plugin :)

**Comment by malles** [comment]
:+1:
