### ISSUE TITLE
Incorrect URL

### ISSUE THREAD

**Issue by Andrew-Spiers** [Bixie/pagekit-portfolio#8]
When I create a new project in my portfolio, it creates a URL of http://andrewspiers.dynu.net/portfolio/photography-website

However the URL should be http://andrewspiers.dynu.net/cms/index.php/portfolio/photography-website

Pagekit is installed into a subdirectory (/cms)

Is there a config option that I have missed or is there a problem with running from a sub directory?

The reset of PageKit i.e. blog works correcrtly.

**Comment by malles** [comment]
I don't see a portfolio menu item in the menu. Try to add the node to an active menu.
Portfolio uses the default Pagekit routing, it should produce the same urls.

**Comment by Andrew-Spiers** [comment]
Thanks, that was the issue. It was not attached to a menu. I found it under "Not Linked". Once I moved it to the main menu, it appeared and the routing was correct.
