### ISSUE TITLE
Portfolio text gone after update?

### ISSUE THREAD

**Issue by ghost** [Bixie/pagekit-portfolio#9]
After upgrading the portfolio plugin to 1.1.2 the description of my portfolio is gone. (portfolio -> settings -> portfolio content) It now only has the default text "<p>This is an overview of my latest projects.</p>" instead of the text I had there before. The projects are present and complete. What happened? Where is this information stored? I don't see any entries in the database.

**Comment by ghost** [comment]
Did some digging. It looks like the data in the table "pk_system_config", entry "bixie/portfolio" is cleared. After restoring this from backups everything is back to normal. This could be a Pagekit issue instead of the Portfolio extension, but that's beyond my skills to assess. Entries in the same table for other extensions that were updated, like the formmaker are not lost when updating.

**Comment by malles** [comment]
The config has moved from entry "portfolio" to "bixie/portfolio" in version 1.1.0. It was migrated in the [update script to 1.1.0](https://github.com/Bixie/pagekit-portfolio/blob/master/scripts.php#L53-L55). I think you updated from version < 1.1.0 to a current version, and there the migration is not executed.

It would mean the entry "portfolio"  is still present in the  "pk_system_config" table, and renaming that to "bixie/portfolio", or copy the contents to that entry would recover your settings.
